name: Backend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # ✅ Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # ✅ Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # ✅ Install dependencies
      - name: Install Dependencies
        run: npm install

      # ✅ Run tests (optional — remove if not needed)
      - name: Run Tests
        run: npm test

      # ✅ Deploy to Server (optional — replace with real deploy commands)
      - name: Deploy Backend
        run: |
          echo "Add backend deployment steps here"
